# Uncomment the following line to enable deep sleep
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=300000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Uncomment the following line to increase the keyboard's wireless range
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Bluetooth stability
CONFIG_BT_MAX_CONN=3
CONFIG_BT_MAX_PAIRED=3
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n
# CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y
CONFIG_BT_CTLR_PHY_2M=n

# Enable eager debouncing
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=10

# Enable ZMK Studio for Realtime Keymap Updates
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
CONFIG_NICE_VIEW_GEM_ANIMATION_MS=1440

# Uncomment the following line to enable USB Logging
# CONFIG_ZMK_USB_LOGGING=y
